name: Codzienna generacja cen

on:
  schedule:
    # codziennie o 7:00 czasu polskiego (w zimie 6:00 UTC, w lecie 5:00 UTC)
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Run script
        run: python "ZaciszeRekowo generuj_ceny.py"

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add ceny.csv

          git commit -m "Automatyczna aktualizacja cen" || echo "Brak zmian do commita"
          git push
